apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: asoze2bx7-nodejs
  janus-idp.io/tekton: asoze2bx7-nodejs
  backstage.io/kubernetes-id: asoze2bx7-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: asoze2bx7-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
